[package]
name = "frpc-transport-http"
version = "0.1.0"
edition = "2021"

[dependencies]
frpc-transport-core = { version = "0.1", path = "../transport-core" }
h2x = { version = "0.6", git = "https://github.com/nurmohammed840/h2x" }
