name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Deno
      uses: denoland/setup-deno@v1.1.2
      with:
        deno-version: v1.x
    
    - name: Run deno test
      run: deno test -A --check
    
    - name: Run cargo clippy
      run: cargo clippy

    - name: Run cargo tests
      run: cargo test
